language: node_js
before_install:
  - "yarn global add serverless"
script:
  - "yarn run lint"
  - "yarn run compile"
  - "echo $TRAVIS_BRANCH"
  - if [ TRAVIS_BRANCH == "master" ]; then yarn deploy; fi
cache: yarn
