# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: plantformio

provider:
  name: aws
  runtime: nodejs8.10

package:
  include:
    - dist/**
  exclude:
    - module/**
    - "**/*.ts"

functions:
  moistureReading:
    handler: lambda/dist/index.handler
    environment:
      WEBHOOK_URL: ${env:WEBHOOK_URL}
      DATADOG_API_KEY: ${env:DATADOG_API_KEY}
    events:
      - iot:
          name: "moistureHandler"
          sql: "SELECT *, topic(2) AS plantName FROM 'plants/+/moisture'"
          description: "Receives plant moisture data and sends it to all the things!"
